version: '3'

services:
  firstwebapplication:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  samplewebapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"